default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: tcb_gp_development
  username: postgres
  password: password
  host: db

test:
  <<: *default
  database: tcb_gp_test
  username: postgres
  password: password
  host: db


production:
  primary: &primary_production
    <<: *default
    database: tcb_gp_production
    url: <%= ENV['DATABASE_URL'] %>
  cache:
    <<: *primary_production
    database: tcb_gp_production_cache
    migrations_paths: db/cache_migrate
    url: <%= ENV['DATABASE_URL'] %>
  queue:
    <<: *primary_production
    database: tcb_gp_production_queue
    migrations_paths: db/queue_migrate
    url: <%= ENV['DATABASE_URL'] %>
