default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: password
  host: db

development:
  <<: *default
  database: tcb_gp_development

test:
  <<: *default
  database: tcb_gp_test


production:
  primary: &primary_production
    <<: *default
    database: tcb_gp_production
    username: app
    password: <%= ENV["tcb_gp_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: tcb_gp_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: tcb_gp_production_queue
    migrations_paths: db/queue_migrate
